version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: land_marketplace_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dawar
      POSTGRES_DB: land-market-place
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  server:
    build: .
    container_name: land_marketplace_server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
