export const notificationItems = [
  {
    id: "listing-approved-popup",
    title: "Listing Approved",
    message: "Your listing \u201cPrime Agriculture Land - Hulu\u201d is now active",
    timeLabel: "Just now",
    type: "success",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "changes-required-popup",
    title: "Changes Required",
    message: "Your listing \u201cSkudai Development\u201d needs document updates",
    timeLabel: "Just now",
    type: "danger",
    href: "/user-dashboard/notifications",
    read: false,
    feedbackTitle: "ADMIN FEEDBACK",
    feedbackMessage: "The uploaded land title scan is blurry. Please upload a high-resolution copy.",
  },
  {
    id: "enquiry-status-popup",
    title: "Enquiry Status Update",
    message: "Your enquiry for \u201cCyberjaya Commercial Plot\u201d has moved to Site Visit",
    timeLabel: "Just now",
    type: "info",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "action-needed-popup",
    title: "Action needed",
    message: "Admin requests more info regarding your recent information",
    timeLabel: "Just now",
    type: "warning",
    href: "/user-dashboard/notifications",
    read: false,
  },
];

export const fullNotificationItems = [
  {
    id: "listing-approved-1",
    title: "Listing Approved",
    message: "Your listing \u201cPrime Agricultural Land - Hulu Langat\u201d is now active",
    timeLabel: "May 24, 09:00 AM",
    type: "success",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "changes-required-1",
    title: "Changes Required",
    message: "Your listing \u201cSkudai Development\u201d needs document updates.",
    timeLabel: "May 24, 09:00 AM",
    type: "danger",
    href: "/user-dashboard/notifications",
    read: false,
    feedbackTitle: "ADMIN FEEDBACK",
    feedbackMessage: "The uploaded land title scan is blurry. Please upload a high-resolution copy.",
  },
  {
    id: "enquiry-status-1",
    title: "Enquiry Status Update",
    message: "Your enquiry for \u201cCyberjaya Commercial Plot\u201d has moved to Site Visit.",
    timeLabel: "May 24, 09:00 AM",
    type: "info",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "listing-approved-2",
    title: "Listing Approved",
    message: "Your listing \u201cPrime Agricultural Land - Hulu Langat\u201d is now active",
    timeLabel: "May 24, 09:00 AM",
    type: "success",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "action-needed-1",
    title: "Action Needed",
    message: "Admin requests more info regarding your recent submission.",
    timeLabel: "May 24, 09:00 AM",
    type: "warning",
    href: "/user-dashboard/notifications",
    read: false,
  },
  {
    id: "enquiry-status-2",
    title: "Enquiry Status Update",
    message: "Your enquiry for \u201cCyberjaya Commercial Plot\u201d has moved to Site Visit.",
    timeLabel: "May 24, 09:00 AM",
    type: "info",
    href: "/user-dashboard/notifications",
    read: true,
  },
];
